---

- name: copy onec srv info script
  win_copy:
    src: "scripts/get-onec-server-service-info.ps1"
    dest: "{{ ansible_win_temp_dir }}\\get-onec-server-service-info.ps1"

- name: retrieving onec server service info
  win_shell: "{{ ansible_win_temp_dir }}\\get-onec-server-service-info.ps1"
  register: onec_server_service_info
- debug: var=onec_server_service_info.stdout_lines

- set_fact:
    onec_server_srv_name: '{{ onec_server_service_info.stdout_lines[0] }}'
    onec_server_srv_params: '{{ onec_server_service_info.stdout_lines[1] }}'
    onec_server_srv_exists: true
  when: onec_server_service_info.stdout_lines | length > 1
- debug:
    msg:
      - "onec_server_srv_name : {{ onec_server_srv_name }}"
      - "onec_server_srv_params : {{ onec_server_srv_params }}"

- name: remove onec server service
  win_service:
    name: '{{ onec_server_srv_name }}'
    state: absent
  when: onec_server_srv_exists is defined and onec_server_srv_exists

- name: check if a RAS service is installed
  win_service:
    name: '{{ ras_srv_name }}'
  register: ras_srv_info
  
- name: remove RAS service
  win_service:
    name: '{{ ras_srv_name }}'
    state: absent
  when: ras_srv_info.exists